// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Orion.Data.Migrations
{
    [DbContext(typeof(OrionDbContext))]
    internal class OrionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Orion.Core.Bar", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("FooId");

                b.Property<int?>("ParentId");

                b.HasKey("Id");

                b.HasIndex("FooId");

                b.HasIndex("ParentId");

                b.ToTable("Bar");
            });

            modelBuilder.Entity("Orion.Core.Baz", b =>
            {
                b.Property<int>("BarId");

                b.HasKey("BarId");

                b.ToTable("Baz");
            });

            modelBuilder.Entity("Orion.Core.BazQux", b =>
            {
                b.Property<int>("BazId");

                b.Property<int>("QuxId");

                b.HasKey("BazId", "QuxId");

                b.HasIndex("QuxId");

                b.ToTable("BazQux");
            });

            modelBuilder.Entity("Orion.Core.Foo", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("UserId");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("Foo");
            });

            modelBuilder.Entity("Orion.Core.Qux", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.HasKey("Id");

                b.ToTable("Qux");
            });

            modelBuilder.Entity("Orion.Core.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.HasKey("Id");

                b.ToTable("User");
            });

            modelBuilder.Entity("Orion.Core.Bar", b =>
            {
                b.HasOne("Orion.Core.Foo", "Foo")
                    .WithMany("Bars")
                    .HasForeignKey("FooId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Orion.Core.Bar", "Parent")
                    .WithMany("Children")
                    .HasForeignKey("ParentId");
            });

            modelBuilder.Entity("Orion.Core.Baz", b =>
            {
                b.HasOne("Orion.Core.Bar", "Bar")
                    .WithOne("Baz")
                    .HasForeignKey("Orion.Core.Baz", "BarId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Orion.Core.BazQux", b =>
            {
                b.HasOne("Orion.Core.Baz", "Baz")
                    .WithMany("Quxes")
                    .HasForeignKey("BazId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Orion.Core.Qux", "Qux")
                    .WithMany("Bazes")
                    .HasForeignKey("QuxId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Orion.Core.Foo", b =>
            {
                b.HasOne("Orion.Core.User", "User")
                    .WithMany("Foos")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}